# Generated by Django 5.2.5 on 2025-09-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
