# Generated by Django 5.2.5 on 2025-09-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
